# Generated by Django 5.1.4 on 2025-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnpayloyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverficationdetails',
            name='otp',
        ),
        migrations.AddField(
            model_name='otpverficationdetails',
            name='secureotp',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='otpverficationdetails',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
