# Generated by Django 5.1.4 on 2025-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnpayloyalty', '0002_remove_otpverficationdetails_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverficationdetails',
            name='points',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
